[package]
name = "watershed_editor"
description = "Bevy editor for watershed terrains."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
watershed.workspace = true
bevy.workspace = true
bevy_egui.workspace = true
serde_json.workspace = true
log.workspace = true
tracing.workspace = true

[lints]
workspace = true
